name: Deploy

on: push


jobs:

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windoiws-latest]
        node: [18,20]

    steps:
      - name: Print Variable
        run: echo "${{ secrets.TOKEN_SECRET }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Instalar Dependencias
        working-directory: ./Example01
        run: npm install

      - name: Run Test
        working-directory: ./Example01
        run: npm run test

      - name: Build page
        working-directory: ./Example01
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Example01/public

  deploy:
    # if: ${{ always() }} # se ejecuta siempre, aunque los anteriores jobs fallen
    runs-on: ubuntu-latest
    needs: build

    # Github pages otorga un token y da grants para poder hacer deploy
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment-pages.outputs.page_url }} # URL de la página desplegada

    steps:
      - name: Deploy
        id: deployment-pages
        uses: actions/deploy-pages@v4

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ always() }}

    steps:
      - name: Notify to slack
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}

        with:
          status: ${{ job.status }}
          fields: repo, commit, author, message, job, took



