name: Deploy to server

on: push

jobs:

  first_job: 
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Step 1, Hola Mundo"

  second_job: 
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Step 2, Hola Mundo"